### ISSUE TITLE
Review Backend JDL

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/Club-Management-Spring-Server#1]
- [x] Check for JDL typo and enhance vocab usage

**Comment by LUXIANZE** [comment]
- [ ] Event Entity - Image should be array of ids
- [ ] Event Crew Enum only HEAD?
- [ ] ChecklistStatus --> IN_PROGRESS
- [ ] BudgetType == TransactionType (should be shared, I suggest use TransactionType only)
- [ ] UserUniStatus --> TRANSFERRED

**Comment by HowardYaw** [comment]
@LUXIANZE 
1. you meaning to allow more than 1 image for an event? if so i think better to have a class between image and event
2. For now i only can think of a event Head, so maybe other crew they have null in the event crew role
3. ok
4. We can do that but it will be meaning the budget type and transaction type will need to be same forever. Else we will ned to append type that is not applicable to transaction on the same enum vice versa.

**Comment by LUXIANZE** [comment]
1. Yes, please do so
2. Ok understood, this may proceed
3. Ok
4. I think can make them same, it is safe since they are both monetary transactions
5. Ok
