### ISSUE TITLE
What is Receipt table and ImageStorage table

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-Spring-Server#39]
At first glance, I am confused with these 2 tables, I thought `Receipt` table is the child of `ImageStorage` table.

But in reality,  `ImageStorage` & `Receipt` table does not have any relationship with each other. 

# ImageStorage table
![image](https://user-images.githubusercontent.com/34387770/99878946-e07c7c00-2bbd-11eb-8107-7373bd536666.png)

ImageStorage stores image related file.  `EventImage` is a join table between `ImageStorage` and `Event` where one Event can have a lot of images.

# Receipt table
![image](https://user-images.githubusercontent.com/34387770/99878967-fbe78700-2bbd-11eb-9bec-51ddf6b0c9ef.png)

Receipt table stores receipt file. 

Am I understand this correctly @HowardYaw ?

**Comment by HowardYaw** [comment]
@kachun333 yes you understand it correct
Image storage will contain all record of images.for now we will only have image for event, if we need we can add images of user in future as well. 
Receipt is containing all receipt. Either we uploaded to cloud storage or it is just a record for the images in the email

**Comment by HowardYaw** [comment]
For receipt table we might need to add a column for receiptId

**Comment by kachun333** [comment]
what do you mean by?
```
For receipt table we might need to add a column for receiptId
```

`receiptId` is foreign key to which table?

**Comment by HowardYaw** [comment]
No a FK. It is a unique id of receipt. Maybe should call receipt_unique_id

**Comment by kachun333** [comment]
yes, `receipt_unique_id` is a better name. 
Shall we close this issue and reopen it only when we want to add this column?

**Comment by HowardYaw** [comment]
let me open a new issue as a task so we wont forget about it later
