### ISSUE TITLE
Integration Test for Security Method Failed

### ISSUE THREAD

**Issue by HowardYaw** [Five-Fishes/Club-Management-Spring-Server#69]
Possible Result:
1. Integration Test MockMvc setup is using standaloneSetup
    - Not able to look for SpringSecurityChainFilter
[Reference](https://stackoverflow.com/a/34316901)

2. Tried to switch to webAppContextSetup with WebApplicationContext
    - But this causing all other tests to be failed

-------

Suggest Solution:
- Create a separate Test for SecurityExpression Methods
    - Drawback will be the Authorization of API endpoints is not well tested

**Comment by kachun333** [comment]
what branch you are on?
All tests run fine on my machine for `dev-version-1` branch

If you still face problem for mockMVC setup, consider using `@AutoConfigureMockMvc` annotation. 

# Example
```
package com.example.testingweb;

import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest
@AutoConfigureMockMvc
public class TestingWebApplicationTest {

	@Autowired
	private MockMvc mockMvc;

	@Test
	public void shouldReturnDefaultMessage() throws Exception {
		this.mockMvc.perform(get("/")).andDo(print()).andExpect(status().isOk())
				.andExpect(content().string(containsString("Hello, World")));
	}
}
```
resources: https://spring.io/guides/gs/testing-web/

**Comment by HowardYaw** [comment]
@kachun333 Thank you for the help
I am working on [create-transaction](https://github.com/Five-Fishes/Club-Management-Spring-Server/tree/create-transaction) branch actually
I just push the latest changes 
You can check out the [PR](https://github.com/Five-Fishes/Club-Management-Spring-Server/pull/51) also


I tried the @AutoConfigureMockMvc, @ContextConfiguration, @ExtendWith
But no luck at all
