### ISSUE TITLE
Custom Authorization Annotation

### ISSUE THREAD

**Issue by HowardYaw** [Five-Fishes/Club-Management-Spring-Server#85]
Create custom Authorization Annotation for testing
Add on
Consider to AND condition

Related to #81

**Comment by HowardYaw** [comment]
Reference
https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html
https://defectracker.com/2019/04/02/custom-annotations-in-testng-scripts/
https://www.baeldung.com/java-custom-annotation

**Comment by kachun333** [comment]
the annotations created in PR #87 are
```
@ WithCurrentCCAdministrator
@ WithCurrentCCHead
@ WithEventCrew
@ WithEventHead
```

`And` condition is not implemented. Since there has a low probability that it will be used.
