### ISSUE TITLE
fetch Account

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-Spring-Server#86]
- Endpoint URI: */api/account*
- Http Method: *GET*
- API Logic: 
  - fetch data from db to produce the response body

- response body
```
  id: number; // userId
  firstName: string;
  email: string;
  imageUrl: string;
  authorities: string[];
  isCurrentCCHead: boolean;
  isCurrentAdministrator: boolean;
  eventHeadEventIds: number[]; // an array of eventId
  eventCrewEventIds: number[]; // an array of eventId
```
- Progress
    - [ ] development
    - [ ] integration Test

**Comment by kachun333** [comment]
if a user is the CC Head. Both `isCurrentCCHead` and `isCurrentAdministrator` will return **`true`**

if a user is a Event Head. Both `eventHeadEventIds` and `eventCrewEventIds` will contains the eventId
e.g.
```
// user is Event Head for eventId 5
eventHeadEventIds = [5]
eventCrewEventIds= [5]
```

**Comment by HowardYaw** [comment]
@kachun333 
since #89 is merged
this issue is resolved right?
or you have any pending task incompleted?
